<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.7.5 on win32)" generated="20240207 08:04:06.443" rpa="true" schemaversion="3">
<suite id="s1" name="Task" source="C:\Users\PC1\PycharmProjects\Appium\Task.robot">
<test id="s1-t1" name="Android App Automation" line="18">
<kw name="Open an Applicaiton">
<kw name="Open Application" library="AppiumLibrary">
<arg>http://localhost:4723</arg>
<arg>platformName=Android</arg>
<arg>deviceName=emulator-5554</arg>
<arg>appPackage=chat21.android.demo</arg>
<arg>appActivity=chat21.android.demo.SplashActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<msg timestamp="20240207 08:04:11.036" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8F84B08&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20240207 08:04:15.124" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8BA7E48&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20240207 08:04:19.211" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8FB8408&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20240207 08:04:23.255" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20240207 08:04:23.254" endtime="20240207 08:04:23.403"/>
</kw>
<msg timestamp="20240207 08:04:23.407" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20240207 08:04:23.410" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8FB8D88&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20240207 08:04:06.939" endtime="20240207 08:04:23.413"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>Hi</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20240207 08:04:23.413" endtime="20240207 08:04:23.414"/>
</kw>
<status status="FAIL" starttime="20240207 08:04:06.938" endtime="20240207 08:04:23.414"/>
</kw>
<status status="FAIL" starttime="20240207 08:04:06.937" endtime="20240207 08:04:23.416">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8FB8D88&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20240207 08:04:06.461" endtime="20240207 08:04:23.421"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tasks</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Task">Task</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240207 08:04:11.036" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8F84B08&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20240207 08:04:15.124" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8BA7E48&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20240207 08:04:19.211" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000027BF8FB8408&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session</msg>
<msg timestamp="20240207 08:04:23.407" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
